[package]
name = "instr_dsl"
version = "0.1.0"
edition = "2021"

[dependencies]
glob = "0.3.1"
lazy_static = "1.4.0"
walrus = { version = "0.20.3" }

# Logging
env_logger = "0.10.2"
log = "0.4.20"

# Pest
pest = "2.7.7"
pest_derive = "2.7.7"
