[package]
name = "whamm"
version = "0.1.0"
edition = "2021"

[[bin]]
doc = false
name = "whamm"
path = "src/main.rs"
required-features = ["exe"]

[dependencies]
failure = "0.1.5"
glob = "0.3.1"
lazy_static = "1.4.0"
regex = "1.10.4"
walrus = "0.20.3"

# Logging
env_logger = "0.10.2"
log = "0.4.20"

# Pest
pest = "2.7.7"
pest_derive = "2.7.7"

# Visualization
graphviz-rust = "0.9.0"

[dependencies.clap]
optional = true
version = "3.2.23"
features = ["derive"]

[features]
default = ["exe"]
exe = ["clap"]
