name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
#    - uses: supplypike/setup-bin@v4
#      with:
#        uri: 'https://github.com/WebAssembly/wabt/releases/download/1.0.34/wabt-1.0.34-ubuntu.tar.gz'
#        name: 'wabt'
#        version: '1.0.34'
    - uses: plinioh/setup-binary-action@v1.0.0
      with:
        binaryName: wasm2wat
        binaryUrl: https://github.com/WebAssembly/wabt/releases/download/1.0.34/wabt-1.0.34-ubuntu.tar.gz
        binaryPathInArchive: wabt-1.0.34/bin/wasm2wat
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
